= Hello World
Scott Laue <laue.scott@gmail.com>
V1.1, 2016-06-07

:hp-tags: general


Famously, "Test Post, Please Ignore" is the inaugural start to new forums. And "Hello World" is the inaugural start to learning a new programming language. I'm not sure what a blog uses, but "Hello World" feels more approriate considering asciidoctor (markup language) will be used extensively for writing here. You may notice this is not a WordPress/Blogger or other major blog site, but a custom built blog forked from the hubpress.github.io repository. Essentially, setting up this blog let me learn many things about site hosting, css, html, and DNS routing. 

===== Tags

I've described this as a semi-technical blog and I will try to keep to that in both aspects. I want to start writing more on technical aspects of my studies and keep writing on things related to my hobbies. I separate them the best I can using the tag system, allowing readers at a glance to skip over topics that may not interest them and for me to find things more easily. Sometimes I need to reread a post I've written to remember a salient point or small detail. 


.Tag System
[horizontal]
* *Knowledge* - the following tags indicate breadth and depth of the post
- *general* - contains information and discussion that should require no or little jargon
- *technical* - contains detailed discipline specific jargon/images that may require prior knowledge
* *Type* - the following tags are types of posts
- *discussion* - general thoughts and relevant links
- *review* - contains a link to a post/article/book with subsequent discussion, summary, further reading
* *<topic>* - contains information and discussion on <topic> and combined with the knowledge and type catagories 

===== Disclaimer

This is not an academic blog and while I will endeavor to cite things properly, I will not always succeed. Rather, this blog is for my own reference and collection.

sl

